### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by gnujeremie** [matthewmueller/x-ray#153]
### Error : Unable to verify the first certificate

When trying to crawl [this page](https://www.arthrocoach.com/fr/actualites/arthrose-generalisee) I get the "unable to verify the first certificate" error.
### Environment
- version of node: _v5.9.0_
- version of npm: _3.7.3_
### Steps to reproduce

Just try to crawl https://www.arthrocoach.com/fr/actualites/arthrose-generalisee.
### Expected behaviour

X-ray should return the value of the scraped elements.
### Actual behaviour

An error is thrown.

Following http://stackoverflow.com/a/32440021/1182487, I added [ssl-root-cas](https://www.npmjs.com/package/ssl-root-cas) to my project, but I does not fix the issue. I don't know if this should be handled by my code, or by X-ray.

**Comment by NetanelBasal** [comment]
+1

**Comment by zeroby0** [comment]
@gnujeremie That's due to an insecure ssl certificate. If you know what you're doing, to ignore ssl verification,  

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`  
Before you use X-ray. once at top of the file probably.

However, it's a **bad idea** to use this. Read a more secure alternative here http://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired#answer-29397100
