### ISSUE TITLE
Select :visible

### ISSUE THREAD

**Issue by roccomuso** [matthewmueller/x-ray#258]
### Selector: `:visible`

How can I use the `:visible` in the selector?
I'm getting an error from cheerio. Are there some workaround?
I'm my sample I have 3 `div`, and one of them got the `.active` class. (For some reason the selector on the `.active` class doesn't work (either on jQuery), and I've been able to get it just using the jQuery `:visible` attr.

### environment:

* version of node: 4.4.0

### Steps to reproduce

selector: `.hello .world:visible`

### Expected behaviour

Select that element.

### Actual behaviour

Cheerio raise an error: `[SyntaxError: unmatched pseudo-class :visible]`

**Comment by gebrits** [comment]
That's because it's not implemented in Cheerio.
See https://github.com/cheeriojs/cheerio/issues/362

**Comment by roccomuso** [comment]
any workaround?

**Comment by gebrits** [comment]
You might have some luck with using a Nightmare driver instead of the
standard Cheerio, since Nightmare apparently supports [visibility selector](
https://github.com/segmentio/nightmare#visibleselector) .

Having said that, I have no idea if the [x-ray nightmare driver](
https://github.com/phulas/x-ray-nightmare) exposes this functionality, etc.
Never used it.

**Comment by lathropd** [comment]
Because cheerio is a parser, not a browser, it doesn't have knowledge of this. Should work in any headless browser.
