### ISSUE TITLE
Crawler support

### ISSUE THREAD

**Issue by kengz** [matthewmueller/x-ray#70]
It's mentioned in the doc that x-ray has crawler support, but it's nowhere to be found in the example.
A quick search leads to another repo `x-ray-crawler`.

Is crawler implemented in x-ray yet? If so is it an importable driver?

**Comment by matthewmueller** [comment]
@kengz You're right, it's not very clear in the docs

Take a look at this example: https://github.com/lapwinglabs/x-ray#crawling-to-another-site

**Comment by kengz** [comment]
Yes, but that internal `x` is a single instance so it scrapes only one site. If I were to follow all the links from a page to the other I suppose for now I'll have to write my own loop that launch a new x-ray instance for each link?

Say, scraping a site with multiple `h2>a` with links, I can then do within an x-ray instance:
```
x(['h2>a@href'], 'p')...// follows all the links in h2, scrape a <p> of each of them
```

**Comment by onbjerg** [comment]
Any update on this? Or should we just use something else entirely, seeing as x-ray does not really work for crawling?

**Comment by kengz** [comment]
A really crappy version I used for my projects. https://github.com/kengz/reqscraper#scrapecrawldyn-url-selector-tailarr

**Comment by matthewmueller** [comment]
sorry guys, i haven't had any free time to work on this for the last month or two. i'd gladly accept a PR to fix this, but if that's too much effort, i'd suggest you give something else a shot for the time being.

i'm not too happy with crawling as is, it's just not flexible enough. next iteration will try to use just regular control flow to do the crawling.

Here's some quick psuedo code:

```ks
while (x('.next-page @href')) {
  yield x('https://dribble.com', '.next-page', {
     title: '.some-title'
  })
}
```

I've realized building this library that the problem space is so vast that coming up with the right API and implementation takes a lot of trial and error and iteration. Unfortunately since I'm not getting paid to do this, I cannot commit as much time as I'd like.

**Comment by demiro** [comment]
I am sure there are plenty of us that would gladly pitch in something to see this library grow with better crawling support and more usable example cases. I'd be the first in the queue

**Comment by gebrits** [comment]
I like x-ray for the incredibly straightforward way to do structured crawling. Sure it could use a couple of extra hooks to add in custom code, but so far I've managed to work with it (extending crawler, adding tor-proxy, etc.) 

Strength of x-ray imho as said is it's structured crawling. Allowing to crawl random sites seems to completely throw the structured crawling aspect overboard. Afterall, how could you crawl in a structured way without knowing the underlying 'template'? 

Seems x-ray needs to decide what it wants to be? :)

Thoughts @matthewmueller?
